name: pandas-datareader-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Runtime
  - python>=3.12
  - lxml
  - pandas>=3.0
  - requests

  # Dev / testing
  - pre-commit
  - ruff
  - coverage
  - codecov
  - coveralls
  - pytest
  - pytest-xdist
  - pytest-cov
  - wrapt

  # Docs
  - sphinx
  - ipython
  - matplotlib
  - requests-cache
  - pydata-sphinx-theme
  - pickleshare

  # Build
  - hatchling
  - hatch-vcs
